language: python
python:
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
  - "3.13"
# command to install dependencies, 
install:
    - pip install -vr requirements.txt||true
# command to run tests, e.g. python setup.py test
script:
- pytest
notifications:
    email: false
    irc:
      channels:
        - "irc.libera.chat#limnoria"
        - "Build #%{build_number}: %{repository} %{branch} (%{commit}) %{author} - %{message}"
        - "Build details: \x03 %{build_url}"
matrix:
    fast_finish: true

